# -*- coding: utf-8 -*-
"""sistem-panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1w5PlGNPp1YhrF2Ur3CWjiWY3s0tG1v
"""

hasil_panen = [100, 150, 200, 125]
total = sum(hasil_panen)
print("Total hasil panen:", total, "kg")

def hitung diskon maksimal(harga_awal, persentase diskon, maks potongan):
potongan = harga_awal * (persentase_diskon/100)

#Batasi nilai potongan jika melebihi batas maksimal
if potongan > maks_potongan:
potongan = maks_potongan

harga akhir = harga_awal - potongan
return harga akhir, potongan

#Contoh penggunaan
harga_barang = 100000
diskon_persen = 50 # 50% dari 100rb seharusnya serb
maksimal_potongan = 20000 # tapi dibatasi maksimal 20rb

harga bayar, potongan dapat hitung diskon maksimal (harga barang, diskon persen, maksimal potongan)
print(f"Harga Barang: Rp{harga barang:,}")
print(f"Potongan Didapat: Rp{potongan dapat,}")
print(f"Total Bayar: Rp{harga bayar,}")
