# -*- coding: utf-8 -*-
"""sistem-panen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1w5PlGNPp1YhrF2Ur3CWjiWY3s0tG1v
"""

hasil_panen = [100, 150, 200, 125]
total = sum(hasil_panen)
print("Total hasil panen:", total, "kg")